### ISSUE TITLE
Preparation of activating the timestamp-based finality feature

### ISSUE THREAD

**Issue by jjyr** [nervosnetwork/godwoken#915]
## Related PR
- https://github.com/godwokenrises/godwoken/pull/836

In `1.8.0-rc2`, we introduce a new finality mechanism [context](https://github.com/godwokenrises/godwoken/blob/d9eb75e69ff135fef18ecf2a777e4a1000f708ff/docs/finality_mechanism_changes.md).

Unfortunately, the upgrading can't be transparent for developers. It requires infrastructures to upgrade their finality determination method. Before activating the feature, we must communicate with the major infrastructures in the Godwoken community and push them to upgrade their code.

Deployment progress:

- [ ] testnet (TBD)
- [ ] mainnet(TBD)

Infrastructures:

- [ ] Explorer
    - [ ] Gwscan Explorer related APIs 
- [ ] Deposit/Withdrawal gateways
    - [ ] Godwoken Bridge
    - [ ] Yokai
- [ ] Wallets
    - [ ] Safepal wallet

**Comment by Flouse** [comment]
# Explanation

1. Previously, `finality_blocks` is a consensus config, see to the rollup_config of mainnet_v1
https://github.com/godwokenrises/godwoken/blob/v1.14.0/crates/config/src/consensus/builtins/mainnet.toml#L178 The consensus constant (in RollupConfig) finality_blocks defines how the last finalized block number is calculated.

2. Since Godwoken v1.7+, the block_time is configurable, we could set mainnet_v1 to 8s, but it will affect the withdrawal finality period, reduce the network security.
https://github.com/godwokenrises/godwoken/blob/v1.14.0/crates/config/src/config.rs#L184-L185

3. Before optimizing Godwoken finality mechanism, if we set the block_time to 8s, then the mainnet_v1 withdrawal finality period will be 
8s * finality_blocks 
= 8s * 16,800 = 2,240mins = 37.3hours => It's a bit too short.

4. A new finality mechanism mentioned in this issue has not been implemented yet, because we have some other higher priority missions.

5. Godwoken provides a faster way to confirm transactions. Once a transaction is verified in the mem-pool, the instant transaction receipt will be generated immediately (in 2s or even faster). This feature is called `Instant Finality`, see https://github.com/godwokenrises/godwoken/blob/develop/web3/docs/addtional-feature.md#instant-finality So, a shorter GW block time may not be a strong requirement.
