### ISSUE TITLE
[BUG] Godwoken incorrectly estimates gas limit

### ISSUE THREAD

**Issue by maciej-kozuszek** [nervosnetwork/godwoken#978]
## **Version**
- Godwoken mainnet v1.1

## **Describe the bug**
Sending transaction without manually set gas limit may fail due to gas limit. This mostly happens when transaction takes more than around 1 million gas limit.
While locally testing contract I noticed that sometimes sending transaction using ethers returns transaction hash (which means ethers has validated transaction and has estimated gas limit) but node returns error with message that transaction failed.

**Expected behavior**

After ethers locally validates transaction it should also be valid when it's sent to node. Manually changing gas limit shouldn't be required.

**Logs**

Failed transaction: https://gwscan.com/tx/0x86a575206f2ee718aa2614dee59f9fd2c5250016465ea6c2c81cb6443750bb19
Succeed transaction with same data but manually set gas limit to 2 million: https://gwscan.com/tx/0x5cb4432fe3ca63eb3ce3d2485b1162a449df24d0a4f5db554eabe5ee5079a626

**Comment by RetricSu** [comment]
> While locally testing contract I noticed that sometimes sending transaction using ethers returns transaction hash (which means ethers has validated transaction and has estimated gas limit) but node returns error with message that transaction failed.

@maciej-kozuszek  did you mean testing the contract locally on [hardhat network](https://hardhat.org/hardhat-network/docs/overview) or on [godwoken-kicker network](https://github.com/godwokenrises/godwoken-kicker)? just want to confirm this. if it is on hardhat network, this might be related to our evm model to estimate gas

**Comment by maciej-kozuszek** [comment]
By locally I meant I ran node.js scripts with contracts calls on local machine on mainnet and testnet network

**Comment by magicalne** [comment]
@maciej-kozuszek Hi, I'm still looking into this issue. I may need your help.
I found something interesting. For the failed tx, the `out of gas` error happened when calling the contract from `0x8f7d6428252a9efeb466780ca6c3a368ca1aef0a`. I cannot access the source code. But I can read the bytecode of the contract. There are some [GAS](https://www.evm.codes/#5a?fork=istanbul)s used in this contract. Looks like the contract routes to different parts based on the current gas left. What I'm trying to say is that the code paths of two transactions(failed and succeed) could be different. Can you please help me check the code? Especially for the last time when calling the contract of `0x8f7d6428252a9efeb466780ca6c3a368ca1aef0a`. This should be related to `gasleft()` or `msg.gas`.

**Comment by maciej-kozuszek** [comment]
My contract doesn't have any conditional branching based on gas left but it's calling flash loan from aave ledning pool at address you listed: `0x8f7d6428252a9efeb466780ca6c3a368ca1aef0a`
It's this contract (here is ethereum mainnet: https://github.com/aave/protocol-v2/blob/master/contracts/protocol/lendingpool/LendingPool.sol) deployed on godwoken at address: https://gwscan.com/account/0x8f7d6428252a9efeb466780ca6c3a368ca1aef0a?search=0x8f7d6428252a9efeb466780ca6c3a368ca1aef0a
I was looking through contract but couldn't find any calls to `gasleft()` or `msg.gas`.

**Comment by magicalne** [comment]
OK. I can confirm this is a bug. I'm sorry I led you in the wrong way. :cry:  The current implementation of opcode `GAS` doesn't use `gas left`. Somehow it uses slightly less than the `gas left`. 
For example, suppose we are going to make a call to some contract, and the gas left is 10000. This call should use 10000 as the gas limit. But it turns out the gas limit is ~9000.
In your case, the estimated gas was right. The last call needed ~1300 gas, I guess only ~300 was set as the gas limit for the call, which is not enough for sure. Then we got a failed tx.

I guess a quick fix is adding more extra gas in the web3 layer. 2000 more should be good. @Flouse

**Comment by Flouse** [comment]
ok. will tune up `EXTRA_ESTIMATE_GAS` env variable of Godwoken testnet_v1 and mainnet_v1.
> https://github.com/godwokenrises/godwoken-info/blob/main/mainnet_v1/web3.env#L22-L23

## New Web3 env variable
```
EXTRA_ESTIMATE_GAS=30000
```

**Comment by Flouse** [comment]
## Memo
https://v1.testnet.gwscan.com/tx/0x9e3808a0c63907803ae1587fd6cac882e882d80cdcb1514b4ebfc6ac01fde7d4
Similar situation reported by a community developer

cc @magicalne @jjyr 

## Temporary workaround solution
Since the gas limit is not guaranteed to be the exact amount of gas required for the transaction, as the actual gas used may be more than the estimated gas. However, adding a margin error percentage can help ensure that the transaction is not rejected due to insufficient gas.

As a simple and temporary workaround solution, please use the estimateGas() function to estimate the gas required for the transaction and then add a 10% margin error to it. You could set the gas limit for the transaction to the final gas limit and then send the transaction.

Hope this helps.

## Reference
- https://stackoverflow.com/questions/70622074/set-gas-limit-on-contract-method-in-ethers-js
